BRmed_cotacao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from rest_framework import routers, serializers, viewsets
from rest_framework.documentation import include_docs_urls

# Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer

# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)


urlpatterns = [
    path('',include('cotacao.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    
    path('docs/', include_docs_urls(title='My API title')),
    path('redoc/', TemplateView.as_view(template_name='redoc.html',extra_context={'schema_url':'openapi-schema'}), name='redoc'),
    path('swagger-ui/', TemplateView.as_view(template_name='swagger-ui.html',extra_context={'schema_url':'openapi-schema'}), name='swagger-ui'),
]

cotacao/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'cotacao'
urlpatterns = [
    path('', views.index, name='index'),
    path('consulta/', views.consulta, name='consulta'),
    url(r'^api/$', views.CotacaoList.as_view(), name='cotacao-list'),
]

cotacao/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    logIp      = models.GenericIPAddressField()
    dt_vl      = models.DateField(auto_now=False)
    vl_brl     = models.DecimalField(max_digits=6, decimal_places=3) 
    vl_ien     = models.DecimalField(max_digits=6, decimal_places=3) 
    vl_eur     = models.DecimalField(max_digits=6, decimal_places=3) 
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

cotacao/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['dt_vl']
 

cotacao/views.py
from django.shortcuts import render, redirect
from rest_framework import generics
from .models import Post
from .serializers import CotacaoSerializer
from .controller.api import ConsultaApi
from .controller.consulta import ConsultaData

def index(request):
    d = ConsultaApi.index()
    esc = []
    for i in d:
        esc.append(
            {
            'id'        : i,
            'data_cotacao'      : d[i]['data'],
            'cotacao'   : {
                            'euro'  : d[i]['euro'],
                            'real'  : d[i]['real'],
                            'ien'   : d[i]['ien'],
                           }
            }
        )
    print(esc)    
    return render(request, 'html/cotacao.html', {'retorno' : esc})

def consulta(request):
    if(request.method == 'GET'):
        return redirect('/')
    else:   
        esc = [] 
        dtinicial   =  request.POST['datei']
        dtfinal     =  request.POST['datef']
        
        DataRetorno = ConsultaData.periodo(dtinicial,dtfinal)
        d = ConsultaApi.postCalendario(DataRetorno)
        for i in d:
            esc.append(
            {
            'id'        : i,
            'data_cotacao'      : d[i]['data'],
            'cotacao'   : {
                            'euro'  : d[i]['euro'],
                            'real'  : d[i]['real'],
                            'ien'   : d[i]['ien'],
                           }
            }
        )
    return render(request, 'html/cotacao.html', {'retorno' : esc})
class CotacaoList(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = CotacaoSerializer

cotacao/templates/html/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa\
9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"/>
</head>
<body>
    <div class="row">
        <div class="col-lg-12">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            {% block consulta %}
            {% endblock %}
        </div>
    </div>
    <div class="row">
        {% block grafico %}
        {% endblock %}
    </div>
        
    <!-- Chartjs libraries -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    {% block js %}
    {% endblock %}
    
</body>
{% load static %}
</html>

cotacao/templates/html/cotacao.html
{% extends 'html/base.html' %}
{% block title %}COTAÇÃO DOLAR{% endblock %}

{% block content %}
    <center>
        <h3>COTAÇÃO DOLAR X REAL-YEN-EURO</h3>
        <br>
    </center>
{% endblock %}

{% block consulta %}
<form action={% url 'cotacao:consulta' %} method="POST">
    {% csrf_token %}
    <center>
        <div class="row">
            <div class="col-lg-2 alert">
                {{ form.as_p }}
            </div>
            <div class="col-lg-4 alert">
                <label>Data inicial</label>
                <input type="date" name="datei" id="datei">
            </div>
            <div class="col-lg-4 alert">
                <label>Data Final</label>
                <input type="date" name="datef" id="datef">
            </div>
            <div class="col-lg-2 alert">
                <button type="submit" class="btn btn-success">Consultar</button>
            </div>
        </div>
        <br>
    </center>
    <br>
    {{ dados }}
</form>
{% endblock %}


{% block grafico %}
    <div class="col-lg-4">
        <div id="euro" class="border"></div>
    </div>

    <div class="col-lg-4">
        <div id="yen" class="border"></div>
    </div>

    <div class="col-lg-4">
        <div id="real" class="border"></div>
    </div>
{% endblock %}


{% block js %}
<script type="text/javascript">
    Highcharts.chart('euro', {
        chart: {
            type: 'line'
        },
        title: {
            text: 'COTAÇÃO DOLAR x EURO'
        },
        subtitle: {
            text: 'Source: api.vatcomply.com/'
        },
        xAxis: {
            categories: [{% for i in retorno %}'{{ i.data_cotacao|safe }}'{% if not forloop.last %},{% endif %}{% endfor %}]
        },
        yAxis: {
            title: {
                text: 'Dolar (USR)'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: [{
            name: 'EURO',
            data: [{% for i in retorno %}{{ i.cotacao.euro|safe }}{% if not forloop.last %},{% endif %}{% endfor %}],
        }]
    });


    Highcharts.chart('yen', {
        chart: {
            type: 'line'
        },
        title: {
            text: 'COTAÇÃO DOLAR x YEN'
        },
        subtitle: {
            text: 'Source: api.vatcomply.com/'
        },
        xAxis: {
            categories: [{% for i in retorno %}'{{ i.data_cotacao|safe }}'{% if not forloop.last %},{% endif %}{% endfor %}]
        },
        yAxis: {
            title: {
                text: 'YEN (JPS)'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: [{
            name: 'YEN',
            data: [{% for i in retorno %}{{ i.cotacao.ien|safe }}{% if not forloop.last %},{% endif %}{% endfor %}],
        }]
    });

    Highcharts.chart('real', {
        chart: {
            type: 'line'
        },
        title: {
            text: "COTAÇÃO DOLAR x REAL"
        },
        subtitle: {
            text: 'Source: api.vatcomply.com/'
        },
        xAxis: {
            categories: [{% for i in retorno %}'{{ i.data_cotacao|safe }}'{% if not forloop.last %},{% endif %}{% endfor %}]
        },
        yAxis: {
            title: {
                text: 'REAL (BRL)'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: [{
            name: 'BRL',
            data: [{% for i in retorno %}{{ i.cotacao.real|safe }}{% if not forloop.last %},{% endif %}{% endfor %}],
        }]
    });


</script>
{% endblock %}

cotacao/templates/redoc.html
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
    <!-- ReDoc doesn't change outer page styles -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='{% url schema_url %}'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>

cotacao/templates/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>